Add wheel perspective, diameterRatio to constructor
AlexLomm/selector_wheel pull request #1
Opened 2023-04-14 10:24 UTC by 1N50MN14

- Added optional wheel `perspective` argument to constructor
  
  - Added optional wheel `diameterRatio` argument to constructor
  
 - Changed `borderRadius` constuctor argument type to `BorderRadiusGeometry` - I understand the reasoning behind behind it being double, however, this grants more flexibility. In my case, I have three selects where I wanted the first to the left to have left radiuses, center none and right with right border radiuses.
 
 - Updated tests, example, changelog and bumped pubspec version

2023-04-14 17:18 UTC, AlexLomm requested changes

2023-04-14 17:18 UTC, AlexLomm commented on lib/selector_wheel/selector_wheel.dart
> +  /// @default BorderRadius.circual(8.0)
There's a typo here

2023-04-14 17:18 UTC, AlexLomm commented on example/pubspec.lock
> +    version: "1.0.4"
I think it makes more sense to make the version "1.1.0" since this is a breaking change 🤔

2023-04-14 17:19 UTC, AlexLomm commented
Thank you for the contribution @1N50MN14! The changes mostly look good, just need tiny changes. After they're made I'll approve

2023-04-15 06:54 UTC, 1N50MN14 commented
@AlexLomm ahhh thanks for spotting the typo! I also bumped pubspec version to `1.1.0`  and updated changelog to reflect the new version as well as highlight breaking change.

2023-04-15 18:09 UTC, AlexLomm commented
Thanks for the updates, I also added some minor tweaks.

2023-04-15 18:14 UTC, merged

2023-04-16 07:04 UTC, 1N50MN14 commented
Thanks @AlexLomm (and thanks for the package)

2023-04-16 15:39 UTC, AlexLomm commented
You're welcome! Thanks for the contribution 👍